apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gphnl2w3t-python 
  janus-idp.io/tekton: gphnl2w3t-python
  backstage.io/kubernetes-id: gphnl2w3t-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gphnl2w3t-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml